AuctionatorConfigurationCopyAndPasteMixin = CreateFromMixins(AuctionatorConfigTooltipMixin)

function AuctionatorConfigurationCopyAndPasteMixin:OnLoad()
  -- 3.3.5a does not reliably materialize FontStrings declared in Layers
  -- when they come from an inherited virtual template. Recreate the label
  -- locally if $parentLabel was not generated by the client.
  if self.Label == nil then
    local name = self.GetName and self:GetName()
    if name then
      self.Label = _G[name .. "Label"]
    end
  end

  if self.Label == nil and self.CreateFontString then
    self.Label = self:CreateFontString(nil, "ARTWORK", "GameFontHighlight")
    if self.InputBox then
      self.Label:SetPoint("TOPLEFT", self.InputBox, "TOPRIGHT", 8, -4)
    else
      self.Label:SetPoint("TOPLEFT", self, "TOPLEFT", 323, -4)
    end
  end

  if self.labelText ~= nil and self.Label then
    self.Label:SetText(self.labelText)
  end

  if self.copyText ~= nil and self.InputBox then
    self.InputBox:SetText(self.copyText)
    self.InputBox:SetCursorPosition(0)
  end
end
